name: project-test

on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.9'
            - name: Install dependencies
              run: |
                  pip install poetry
                  make install
            - name: Running linter
              run: make lint
            - name: Doing tests
              run: make test
